name: frontend

on:
  push:
    paths:
    - ".github/workflows/frontend.yml"
    - ".github/workflows/sync-html.yml"
    - "html/**"
    - "src/html.h"
    - "test/font-check.js"
  pull_request:
    paths:
    - ".github/workflows/frontend.yml"
    - ".github/workflows/sync-html.yml"
    - "html/**"
    - "src/html.h"
    - "test/font-check.js"

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 18
      - name: Build the frontend
        run: |
          corepack enable
          yarn install --immutable
          yarn run check
          yarn run build
        working-directory: html
